name: Sync Icons to JSON

on:
  push:
    paths:
    - 'icons/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Sync icons to JSON
      run: |
        ICONS_JSON='{"icons": []}'
        for icon in icons/*; do
          ICON_NAME=$(basename "$icon" .svg)  # Assuming SVG icons
          ICONS_JSON=$(echo "$ICONS_JSON" | jq ".icons += [\"$ICON_NAME\"]")
        done
        echo "$ICONS_JSON" > icons.json
        
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add icons.json
        git commit -m "Sync icons to JSON" || echo "No changes to commit"
        git push origin HEAD || echo "No changes to push"
